### ISSUE TITLE
/v1/delete-ltp-and-dependents is not deleting the records inside ES

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#409]
We are registering an application called "VeryDummyApplication"
This is getting updated in the ALT with update-ltp.
But , while deregistering this application , the values are not getting deleted eventhough the /v1/delete-ltp-and-dependents is successful in the EATL records.

```
[
  {
    "x-correlator": "550e0132-e29b-71d4-a716-446655448163",
    "trace-indicator": "1",
    "user": "User Name",
    "originator": "Testing",
    "application-name": "RegistryOffice",
    "release-number": "2.0.1",
    "operation-name": "/v1/deregister-application",
    "response-code": 204
  },
  {
    "x-correlator": "550e0132-e29b-71d4-a716-446655448163",
    "trace-indicator": "1.1",
    "user": "User Name",
    "originator": "RegistryOffice",
    "application-name": "TypeApprovalRegister",
    "release-number": "2.0.1",
    "operation-name": "/v1/disregard-application",
    "response-code": 204
  },
  {
    "x-correlator": "550e0132-e29b-71d4-a716-446655448163",
    "trace-indicator": "1.3",
    "user": "User Name",
    "originator": "RegistryOffice",
    "application-name": "OamLog",
    "release-number": "2.0.1",
    "operation-name": "/v1/disregard-application",
    "response-code": 204
  },
  {
    "x-correlator": "550e0132-e29b-71d4-a716-446655448163",
    "trace-indicator": "1.4",
    "user": "User Name",
    "originator": "RegistryOffice",
    "application-name": "AdministratorAdministration",
    "release-number": "2.0.1",
    "operation-name": "/v1/disregard-application",
    "response-code": 204
  },
  {
    "x-correlator": "550e0132-e29b-71d4-a716-446655448163",
    "trace-indicator": "1.6",
    "user": "User Name",
    "originator": "RegistryOffice",
    "application-name": "OperationKeyManagement",
    "release-number": "2.0.1",
    "operation-name": "/v1/disregard-application",
    "response-code": 204
  },
  {
    "x-correlator": "550e0132-e29b-71d4-a716-446655448163",
    "trace-indicator": "1.2",
    "user": "User Name",
    "originator": "RegistryOffice",
    "application-name": "ExecutionAndTraceLog",
    "release-number": "2.0.1",
    "operation-name": "/v1/disregard-application",
    "response-code": 204
  },
  {
    "x-correlator": "550e0132-e29b-71d4-a716-446655448163",
    "trace-indicator": "1.5",
    "user": "User Name",
    "originator": "RegistryOffice",
    "application-name": "ApplicationLayerTopology",
    "release-number": "2.0.1",
    "operation-name": "/v1/disregard-application",
    "response-code": 204
  },
  {
    "x-correlator": "550e0132-e29b-71d4-a716-446655448163",
    "trace-indicator": "1.8",
    "user": "User Name",
    "originator": "RegistryOffice",
    "application-name": "ApplicationLayerTopology",
    "release-number": "2.0.1",
    "operation-name": "/v1/delete-ltp-and-dependents",
    "response-code": 204
  },
  {
    "x-correlator": "550e0132-e29b-71d4-a716-446655448163",
    "trace-indicator": "1.7",
    "user": "User Name",
    "originator": "RegistryOffice",
    "application-name": "ApplicationLayerTopology",
    "release-number": "2.0.1",
    "operation-name": "/v1/delete-ltp-and-dependents",
    "response-code": 204
  },
  {
    "x-correlator": "550e0132-e29b-71d4-a716-446655448163",
    "trace-indicator": "1.10",
    "user": "User Name",
    "originator": "RegistryOffice",
    "application-name": "ApplicationLayerTopology",
    "release-number": "2.0.1",
    "operation-name": "/v1/delete-ltp-and-dependents",
    "response-code": 204
  },
  {
    "x-correlator": "550e0132-e29b-71d4-a716-446655448163",
    "trace-indicator": "1.11",
    "user": "User Name",
    "originator": "RegistryOffice",
    "application-name": "ApplicationLayerTopology",
    "release-number": "2.0.1",
    "operation-name": "/v1/delete-ltp-and-dependents",
    "response-code": 204
  },
  {
    "x-correlator": "550e0132-e29b-71d4-a716-446655448163",
    "trace-indicator": "1.9",
    "user": "User Name",
    "originator": "RegistryOffice",
    "application-name": "ApplicationLayerTopology",
    "release-number": "2.0.1",
    "operation-name": "/v1/delete-ltp-and-dependents",
    "response-code": 204
  }
]
```
Logs:
```
Elasticsearch error occurred: {"took":3,"timed_out":false,"total":1,"updated":0,"deleted":0,"batches":1,"version_conflicts":1,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":-1,"throttled_until_millis":0,"failures":[{"index":"alt-2-0-1-000001","id":"MotBLogBoO4BMZYqzt7S","cause":{"type":"version_conflict_engine_exception","reason":"[MotBLogBoO4BMZYqzt7S]: version conflict, required seqNo [11900], primary term [1]. current document has seqNo [11901] and primary term [1]","index_uuid":"qHmph0zURr2z07g2ve0_YQ","shard":"0","index":"alt-2-0-1-000001"},"status":409}]}
(node:1) UnhandledPromiseRejectionWarning: ResponseError: {"took":3,"timed_out":false,"total":1,"updated":0,"deleted":0,"batches":1,"version_conflicts":1,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":-1,"throttled_until_millis":0,"failures":[{"index":"alt-2-0-1-000001","id":"MotBLogBoO4BMZYqzt7S","cause":{"type":"version_conflict_engine_exception","reason":"[MotBLogBoO4BMZYqzt7S]: version conflict, required seqNo [11900], primary term [1]. current document has seqNo [11901] and primary term [1]","index_uuid":"qHmph0zURr2z07g2ve0_YQ","shard":"0","index":"alt-2-0-1-000001"},"status":409}]}
    at onBody (/home/openbackhaul/applicationLayerTopology/node_modules/@elastic/elasticsearch/lib/Transport.js:367:23)
    at IncomingMessage.onEnd (/home/openbackhaul/applicationLayerTopology/node_modules/@elastic/elasticsearch/lib/Transport.js:291:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 180)
Elasticsearch error occurred: {"took":3,"timed_out":false,"total":1,"updated":0,"deleted":0,"batches":1,"version_conflicts":1,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":-1,"throttled_until_millis":0,"failures":[{"index":"alt-2-0-1-000001","id":"MotBLogBoO4BMZYqzt7S","cause":{"type":"version_conflict_engine_exception","reason":"[MotBLogBoO4BMZYqzt7S]: version conflict, required seqNo [11900], primary term [1]. current document has seqNo [11901] and primary term [1]","index_uuid":"qHmph0zURr2z07g2ve0_YQ","shard":"0","index":"alt-2-0-1-000001"},"status":409}]}
(node:1) UnhandledPromiseRejectionWarning: ResponseError: {"took":3,"timed_out":false,"total":1,"updated":0,"deleted":0,"batches":1,"version_conflicts":1,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":-1,"throttled_until_millis":0,"failures":[{"index":"alt-2-0-1-000001","id":"MotBLogBoO4BMZYqzt7S","cause":{"type":"version_conflict_engine_exception","reason":"[MotBLogBoO4BMZYqzt7S]: version conflict, required seqNo [11900], primary term [1]. current document has seqNo [11901] and primary term [1]","index_uuid":"qHmph0zURr2z07g2ve0_YQ","shard":"0","index":"alt-2-0-1-000001"},"status":409}]}
    at onBody (/home/openbackhaul/applicationLayerTopology/node_modules/@elastic/elasticsearch/lib/Transport.js:367:23)
    at IncomingMessage.onEnd (/home/openbackhaul/applicationLayerTopology/node_modules/@elastic/elasticsearch/lib/Transport.js:291:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 181)

```

> Priority:High;

**Comment by DanaSunal** [comment]
Can you please provide curl for both requests? It makes it easier to replicate otherwise I'll spend at least 2h trying to recreate the scenario. Output from EATL is not helping in this case.

**Comment by PrathibaJee** [comment]
1. /v1/register-application in RegistryOffice
```
curl -X POST "http://x.x.x.x:3000/v1/register-application" -H "accept: application/json" -H "user: User Name" -H "originator: RecordSequenceRepresentation" -H "x-correlator: 550e8400-e29b-11d4-a716-446655440567" -H "trace-indicator: 1" -H "customer-journey: Unknown value" -H "Content-Type: application/json" -d "{\"application-name\":\"RecordSequenceRepresentation\",\"release-number\":\"2.0.1\",\"preceding-application-name\":\"RecordSequenceRepresentation\",\"preceding-release-number\":\"1.0.0\",\"embedding-operation\":\"/v1/embed-yourself\",\"client-update-operation\":\"/v1/update-client\",\"operation-client-update-operation\":\"/v1/update-operation-client\",\"tcp-server-list\":[{\"protocol\":\"HTTP\",\"address\":{\"ip-address\":{\"ipv-4-address\":\"1.1.3.9\"}},\"port\":3009},{\"protocol\":\"HTTPS\",\"address\":{\"ip-address\":{\"ipv-4-address\":\"1.2.3.9\"}},\"port\":3209}]}"
```

2. /v1/list-records-of-flow with "x-correlator: 550e8400-e29b-11d4-a716-446655440567" (used for registration)
update-ltp and update-fc to ApplicationLayerTopology is 204 for the registered applcation.
```
  {
    "x-correlator": "550e8400-e29b-11d4-a716-446655440567",
    "trace-indicator": "1.8",
    "user": "User Name",
    "originator": "RegistryOffice",
    "application-name": "ApplicationLayerTopology",
    "release-number": "2.0.1",
    "operation-name": "/v1/update-fc",
    "response-code": 204
  },
  {
    "x-correlator": "550e8400-e29b-11d4-a716-446655440567",
    "trace-indicator": "1.3",
    "user": "User Name",
    "originator": "RegistryOffice",
    "application-name": "ApplicationLayerTopology",
    "release-number": "2.0.1",
    "operation-name": "/v1/update-ltp",
    "response-code": 204
  },
  {
    "x-correlator": "550e8400-e29b-11d4-a716-446655440567",
    "trace-indicator": "1.5",
    "user": "User Name",
    "originator": "RegistryOffice",
    "application-name": "ApplicationLayerTopology",
    "release-number": "2.0.1",
    "operation-name": "/v1/update-ltp",
    "response-code": 204
  },
  {
    "x-correlator": "550e8400-e29b-11d4-a716-446655440567",
    "trace-indicator": "1.2",
    "user": "User Name",
    "originator": "RegistryOffice",
    "application-name": "ApplicationLayerTopology",
    "release-number": "2.0.1",
    "operation-name": "/v1/update-ltp",
    "response-code": 204
  },
  {
    "x-correlator": "550e8400-e29b-11d4-a716-446655440567",
    "trace-indicator": "1.4",
    "user": "User Name",
    "originator": "RegistryOffice",
    "application-name": "ApplicationLayerTopology",
    "release-number": "2.0.1",
    "operation-name": "/v1/update-ltp",
    "response-code": 204
  },
  {
    "x-correlator": "550e8400-e29b-11d4-a716-446655440567",
    "trace-indicator": "1.6",
    "user": "User Name",
    "originator": "RegistryOffice",
    "application-name": "ApplicationLayerTopology",
    "release-number": "2.0.1",
    "operation-name": "/v1/update-ltp",
    "response-code": 204
  },
  {
    "x-correlator": "550e8400-e29b-11d4-a716-446655440567",
    "trace-indicator": "1.7",
    "user": "User Name",
    "originator": "RegistryOffice",
    "application-name": "ApplicationLayerTopology",
    "release-number": "2.0.1",
    "operation-name": "/v1/update-ltp",
    "response-code": 204
  }
```
3. In ALT , check the /v1/list-operation-clients-at-application 
```
curl -X POST "http://x.x.x.x:3005/v1/list-operation-clients-at-application" -H "accept: application/json" -H "user: User Name" -H "originator: Resolver" -H "x-correlator: 410e8400-e29b-11d4-a716-446655440000" -H "trace-indicator: 1" -H "customer-journey: Unknown value" -H "operation-key: Operation key not yet provided." -H "Content-Type: application/json" -d "{\"application-name\":\"RegistryOffice\",\"release-number\":\"2.0.1\"}"
```
Please find the sample output  [response_1689236702130.txt]https://github.com/openBackhaul/ApplicationLayerTopology/files/12037760/response_1689236702130.txt), where the registered application's /v1/embed-yourself is missing

Also , in the /app/dev_tools# of Elastic search , could not able to see entries created for the Registered application either in the LTP/FC

**Comment by PrathibaJee** [comment]
Assertion failure details
- SERVICELAYER / INDIVIDUALPART / /V1/REGARD-APPLICATION / ACCEPTANCE / UPDATE FC NOTIFIED? / CLIENT CREATE
Expected ExecutionAndTraceLog/v1/list-records-of-flow
- SERVICELAYER / INDIVIDUALPART / /V1/DISREGARD-APPLICATION / ACCEPTANCE / DELETE LTP AND DEPENDENTS NOTIFIED? / CLIENT DELETE
Expected ExecutionAndTraceLog/v1/list-records-of-flow

**Comment by DanaSunal** [comment]
I think we have two separate issues here. In your steps to reproduce you don't mention the error 'version mismatch' and also delete-ltp-and-dependants is not called in this scenario.

**Comment by DanaSunal** [comment]
I have created an issue in RO for the use case you described in the comment last week. openBackhaul/RegistryOffice#492
I tested the version mismatch issue and found out, that RO does not send all the LTPs to ALT. Hence ALT does not create data in ES.

The problem with version mismatch should be solved by implementing Async Lock on ES transactions. I will create a pull request today.
